name = "snowglake"
version = "0.1.0"
licences = ["Apache-2.0"]
description = "Gleam version of the Twitter's snowflake format for unique IDs."

repository = { type = "github", user = "mikan-laboratory", repo = "snowglake" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_otp = ">= 1.2.0 and < 2.0.0"
gleam_time = ">= 1.4.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
